<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"UTF-8\">";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
echo "<title>PantryChef</title>";
echo "<link rel=\"stylesheet\" href=\"shared.css\">";
echo "<link rel=\"stylesheet\" href=\"index.css\">";
echo "<!-- Apply dark mode before paint to prevent flash -->";
echo "<script>if(localStorage.getItem('theme')==='dark')document.documentElement.classList.add('dark');</script>";
echo "</head>";
echo "<body>";
echo "";
echo "<header>";
echo "<div class=\"logo\" onclick=\"location.href='index.php'\">PantryChef</div>";
echo "<nav class=\"h-nav\">";
echo "<button class=\"nav-btn active\">Home</button>";
echo "<button class=\"nav-btn\" onclick=\"location.href='inventory.php'\">Inventory</button>";
echo "</nav>";
echo "<div class=\"h-right\">";
echo "<span id=\"userBadge\"></span>";
echo "<button class=\"btn-theme\" onclick=\"toggleTheme()\" title=\"Toggle dark mode\">🌙</button>";
echo "<button class=\"btn-signin\" id=\"btnSignIn\" onclick=\"location.href='login.php'\">Sign In</button>";
echo "<button class=\"btn-logout\" id=\"btnLogout\" onclick=\"doLogout()\">Sign Out</button>";
echo "</div>";
echo "</header>";
echo "";
echo "<div class=\"toast\" id=\"toast\"></div>";
echo "";
echo "<div class=\"page\">";
echo "<div class=\"page-title\">Search Recipes</div>";
echo "<div class=\"page-sub\">Add ingredients to find matching recipes.</div>";
echo "";
echo "<div class=\"input-card\">";
echo "<div class=\"input-row\">";
echo "<div class=\"af-wrap\">";
echo "<input id=\"ingName\" type=\"text\" placeholder=\"Ingredient name…\" autocomplete=\"off\">";
echo "<div id=\"suggestions\"></div>";
echo "</div>";
echo "<input id=\"ingQty\" class=\"qty-inp\" type=\"number\" placeholder=\"Qty\" min=\"0.01\" step=\"any\">";
echo "<select id=\"ingUnit\" class=\"unit-sel\">";
echo "<option>g</option><option>kg</option><option>ml</option><option>L</option>";
echo "<option>cups</option><option>tbsp</option><option>tsp</option>";
echo "<option selected>pcs</option>";
echo "</select>";
echo "<button class=\"btn-add-ing\" id=\"btnAddIng\" onclick=\"addIng()\" title=\"Add\" disabled>+</button>";
echo "<button class=\"btn-clear-ing\" onclick=\"clearForm()\" title=\"Clear\">✕</button>";
echo "</div>";
echo "";
echo "";
echo "<div class=\"time-filter\">";
echo "<label for=\"timeRange\">Max cooking time: <span id=\"timeValue\">30</span> min</label>";
echo "<input type=\"range\" id=\"timeRange\" min=\"0\" max=\"180\" step=\"5\" value=\"30\" oninput=\"updateTimeValue()\">";
echo "</div>";
echo "<button class=\"common-toggle\" id=\"commonToggle\" onclick=\"toggleCommon()\">";
echo "<svg width=\"12\" height=\"12\" viewBox=\"0 0 12 12\" fill=\"none\">";
echo "<path d=\"M2 4l4 4 4-4\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>";
echo "</svg>";
echo "Common ingredients";
echo "</button>";
echo "<div class=\"common-grid\" id=\"commonGrid\"></div>";
echo "";
echo "<div class=\"ing-chips-section\" id=\"chipsSection\" style=\"display:none\">";
echo "<div class=\"ing-chips-label\" id=\"chipsLabel\">YOUR INGREDIENTS (0)</div>";
echo "<div class=\"ing-chips\" id=\"chipsList\"></div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"results-section\" id=\"resultsSection\" style=\"display:none\">";
echo "<div class=\"results-label\" id=\"resultsLabel\"></div>";
echo "<div class=\"results-grid\" id=\"resultsGrid\"></div>";
echo "</div>";
echo "<div class=\"results-empty\" id=\"resultsEmpty\">";
echo "<span class=\"results-empty-ico\">🍳</span>";
echo "<p>Add ingredients above to find matching recipes.</p>";
echo "</div>";
echo "</div>";
echo "";
echo "<script src=\"shared.js\"></script>";
echo "<script src=\"index.js\"></script>";
echo "</body>";
echo "</html>";
?>
