<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"UTF-8\">";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
echo "<title>PantryChef — Inventory</title>";
echo "<link rel=\"stylesheet\" href=\"shared.css\">";
echo "<link rel=\"stylesheet\" href=\"inventory.css\">";
echo "<script>if(localStorage.getItem('theme')==='dark')document.documentElement.classList.add('dark');</script>";
echo "</head>";
echo "<body>";
echo "";
echo "<header>";
echo "<div class=\"logo\" onclick=\"location.href='index.php'\">PantryChef</div>";
echo "<nav class=\"h-nav\">";
echo "<button class=\"nav-btn\" onclick=\"location.href='index.php'\">Home</button>";
echo  "<button class=\"nav-btn\" onclick=\"location.href='browse_recipes.php'\">Browse Recipes</button>";
echo "<button class=\"nav-btn active\">User Ingredients</button>";
echo "</nav>";
echo "<div class=\"h-right\">";
echo "<a id=\"userBadge\" href=\"profile.php\"></a>";
echo "<button class=\"btn-theme\" onclick=\"toggleTheme()\" title=\"Toggle dark mode\">🌙</button>";
echo "<button class=\"btn-signin\" id=\"btnSignIn\" onclick=\"location.href='login.php'\">Sign In</button>";
echo "<button class=\"btn-logout\" id=\"btnLogout\" onclick=\"doLogout()\">Sign Out</button>";
echo "</div>";
echo "</header>";
echo "";
echo "<div class=\"toast\" id=\"toast\"></div>";
echo "";
echo "<div class=\"inv-main\">";
echo "<div class=\"inv-hdr\">";
echo "<h2>Your Inventory</h2>";
echo "<div class=\"inv-tools\">";
echo "<div class=\"search-wrap\">";
echo "<span class=\"search-icon\">🔍</span>";
echo "<input id=\"search\" type=\"text\" placeholder=\"Search ingredients…\">";
echo "</div>";
echo "<select id=\"sortExpiry\" class=\"sort-sel\">";
echo "<option value=\"default\">Default</option>";
echo "<option value=\"name_asc\">Name A-Z</option>";
echo "<option value=\"name_desc\">Name Z-A</option>";
echo "<option value=\"amount_asc\">Amount: Low to High</option>";
echo "<option value=\"amount_desc\">Amount: High to Low</option>";
echo "<option value=\"expiry_asc\">Closest expiration date</option>";
echo "</select>";
echo "</div>";
echo "</div>";
echo "<div id=\"list\"></div>";
echo "</div>";
echo "";
echo "<!-- Confirm dialog -->";
echo "<div class=\"overlay\" id=\"overlay\">";
echo "<div class=\"dialog\">";
echo "<h3>Remove ingredient?</h3>";
echo "<p id=\"dlgMsg\"></p>";
echo "<div class=\"dlg-btns\">";
echo "<button class=\"btn-cancel\" id=\"btnNo\">Cancel</button>";
echo "<button class=\"btn-danger\" id=\"btnYes\">Remove</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Undo bar -->";
echo "<div class=\"undo-bar\" id=\"undoBar\">";
echo "<span id=\"undoMsg\"></span>";
echo "<button class=\"btn-undo\" onclick=\"undoRemove()\">Undo</button>";
echo "</div>";
echo "";
echo "<script src=\"shared.js\"></script>";
echo "<script src=\"inventory.js\"></script>";
echo "</body>";
echo "</html>";
echo "";
?>
